version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_banco
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
